### ISSUE TITLE
The output of  ssrf.yaml doesn't exist in out/jaeles-summary.txt

### ISSUE THREAD

**Issue by MohamedTarekq** [ghsec/ghsec-jaeles-signatures#1]
when i use  ``` jaeles scan -u http://example.com/path?param=something -s ssrf.yaml -p "dest=yourServer" ```

 Summary output: out/jaeles-summary.txt
  INFO Signatures Loaded: 1
  INFO Signature Loaded: ssrf.yaml
  INFO Start Scan with ID: 38666366343833362d303138312d313165622d626463302d313664353636306165353362
 INFO Input Loaded: 1
 INFO Sending request with Parallel mode.

but in fact there were not any output or information in out/jaeles-summary.txt about ssrf

**Comment by ghsec** [comment]
Good question. Need look in collaborator tab or using ypur server and listen port with nc or netcat.

If you notice I am detecting ssrfHere in response.
It detects this if you have created file which conteins ssrfhere keyword.

In my situation I am using ngrok.
1. Create ssrf.txt file in /var/www/html and wryte ssrfHere word in this file.
2. Run ngrok in terminal
ngrok http 80

Run jaeles with command

jaeles -u url -s ssrf.yaml -p "dest=ngrokserver/ssrf.txt"
If you have ssrf vuln  "not blind" vulnerable server mist load your ssrf.txt content.

**Comment by MohamedTarekq** [comment]
First i'd thank you for quick response 
 in my case i used collaborator server and passed to jaeles urls.txt
and i found interaction with my burp but i can't know where the vulnerable url from my urls.txt

**Comment by ghsec** [comment]
Yes it is common problem for me. But I have one tweek for this.
In signature is generators part where signature generates request.
Example:

generators:
  - Query("{{.payload}}{{.Url}}")

I dont test this yet it is only idea. Try this and ping me back here or on twitter.

**Comment by ghsec** [comment]
@MohamedTarekq  yes method works. I tested.

```
id: SSRF
type: fuzz
info:
  name: SSRF
  risk: High

# jaeles scan -p 'dest=xx.burpcollaborator.net' ...
params:
  - dest: '{{.oob}}'

payloads:
  - "{{.dest}}"
  - https://{{.dest}} 
  - http://{{.dest}}


requests:
  - redirect: true
    generators:
      - Query("{{.payload}}/{{.URL}}")

```

detection part not need because you can detect in burp collab window

my ngrok output is

```
Connections                   ttl     opn     rt1     rt5     p50     p90       
                              1       0       0.00    0.00    5.01    5.01      
                                                                                
HTTP Requests                                                                   
-------------                                                                   
                                                                                
GET /http://VunerbleHost/plugins/servlet/oauth/users/icon-uri 404 Not Found  
```

**Comment by MohamedTarekq** [comment]
awesome man i really appreciate your works thank you ☻
